name: Build and publish to ghcr

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test postgres integrations
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Test postgres integration
        run: |
          deno run test:integration
  build:
    name: Build container
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: query-doctor/sync
    permissions:
      id-token: write
      contents: read
      attestations: write
      packages: write
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - runs-on: ubuntu-24.04
            platform: linux/amd64
          - runs-on: ubuntu-24.04-arm
            platform: linux/arm64
    steps:
      - uses: actions/checkout@v3
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set sync_version from deno.json
        run: |
          platform=${{ matrix.platform }}
          sync_version=$(jq -r '.version' deno.json)
          echo "sync_version=${sync_version}" >> $GITHUB_ENV
      - name: Build and push @query-doctor/sync
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.sync_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
